name: Project Deployment

on:
  release:
    types: [published]

jobs:
  backend_deploy:
    name: Backend Deployment in Render
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: ./auto_selecto
          file: ./auto_selecto/Dockerfile
          push: true
          tags: ${{ github.repository }}-backend:latest, ${{ secrets.BACK_REPOSITORY }}:${{ github.ref_name }}
          labels: backend

      - name: Deploy to Render (Production)
        run: curl --request GET \ --url ${{ secrets.RENDER_BACKEND }}


  frontend_deploy:
    name: Deployment frontend in Render
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: ./client
          file: ./client/Dockerfile
          push: true
          tags: ${{ github.repository }}-frontend:latest, ${{ secrets.FRONT_REPOSITORY }}:${{ github.ref_name }}
          labels: frontend

      - name: Deploy to Render (Production)
        run: curl --request GET \ --url ${{ secrets.RENDER_FRONTEND }}